#!/bin/bash

export DANSSRAWREC_HOME=/usr/local/digi/

BUILDER=./digi_evtbuilder3

if [ "X"$1 == "X" ] ; then
	echo "Usage ./evtbuilder3 run_number|-mfilename [flags] [root_dir]"
	exit 10
fi

FLAGS=${2:-"0x50000"}
ROOT_DIR=${3:-"danss_root3"}

if [ ${1:0:2} == "-m" ] ; then
	RUN=${1/-m/}

	LISTFILE=".mc.list"
	echo $RUN > $LISTFILE
	OUTFILE=$ROOT_DIR/`basename $RUN`
#	CALIB="danss_data_002101-17_calib.txt"

	$BUILDER -file $LISTFILE -output ${OUTFILE/.digi/.root} -flag $FLAGS -mcdata -alen 285.0
else
	RUNNUMBER=`printf "%6.6d" $1`
	RUN=`find /space/digi -name danss*${RUNNUMBER}_rawrec_*digi* -print -quit 2>/dev/null`

	if [ "x$RUN" == "x" ] ; then
    		echo Run $RUNNUMBER not found
	    	exit 10
	fi

	if [ $RUN != ${RUN/.bz2} ] ; then
		bzip2 -d -k $RUN
		RUN=${RUN/.bz2}
	fi

	LISTFILE="${RUNNUMBER}.list"
	echo $RUN > $LISTFILE

	RUNDIR=`dirname $RUN`
	CALIB=`find $RUNDIR -name "*calib.txt" -print`

	if [ "x$CALIB" == "x" ] ; then
		echo "No calibration found in $RUNDIR - using default"
		CALIB="danss_data_002101-17_calib.txt"
	fi

	if [ $RUNNUMBER -lt 2066 ] ; then
		TCALIB=tcalib_1000_ss.calib
	else
		TCALIB=tcalib_cmnew_ss.calib
	fi

	$BUILDER -calib $CALIB -file $LISTFILE -tcalib $TCALIB -output ${ROOT_DIR}/danss_${RUNNUMBER}.root -flag $FLAGS
fi

rm $LISTFILE

if [ -f ${RUN}.bz2 ] ; then
	echo rm ${RUN}
fi
