#!/bin/bash

if [ "X"$2 == "X" ] ; then
	echo "Usage ./run_evt first_number last_number [flags] [root_dir]"
	exit 10
fi

FLAGS=${3:-"0x50002"}
ROOT_DIR=${4:-"danss_root4"}
LOG_FILE="$1-$2-evtbuilder.log"
rm -f $LOG_FILE 2> /dev/null

for ((i=$1; $i < $2+1; i=$i+1)) ; do 
	./evtbuilder4 $i $FLAGS $ROOT_DIR >> $LOG_FILE 2>&1
done

