#!/bin/bash

if [ "X"$2 == "X" ] ; then
	echo "Usage $0 first_number last_number"
	exit 10
fi

FIRST=$1
LAST=$2
TOTAL=$(($LAST - $FIRST + 1))
USECPU=8

if [ $LAST -lt $FIRST ] ; then
	echo Nothing to do !
	exit 100
fi

if [ $TOTAL -lt $USECPU ] ; then
	USECPU=$TOTAL
fi

portion=$(($TOTAL/$USECPU))
rest=$(($TOTAL - $USECPU * $portion))

for ((i=0; $i < $USECPU; i=$i+1)) ; do 
	begin=$(($FIRST + $i * $portion))
	end=$(($begin + $portion - 1))
	if [ $i == $(($USECPU - 1)) ] ; then
		end=$(($end+$rest))
	fi
	nohup ./run_pair $begin $end &
done
