#!/bin/bash

if [ "X"$2 == "X" ] ; then
	echo "Usage ./run_evt first_number last_number [flags] [root_dir]"
	exit 10
fi

FLAGS=${3:-"0x80000"}
ROOT_DIR=${4:-"danss_root"}

for ((i=$1; $i < $2+1; i=$i+1)) ; do ./evtbuilder $i $FLAGS $ROOT_DIR ; done

